import { PrismaClient } from "@prisma/client";
import { NextResponse } from "next/server";
import admin from "firebase-admin";

const prisma = new PrismaClient();
const VERIFY_TOKEN = "mySecretAlertifyToken2025";

// Define the Emergency type based on your Prisma schema
interface Emergency {
  id?: string; // Optional since it’s auto-generated by Prisma
  emergency: string;
  lat: string;
  long: string;
  barangay: string;
  munName:string;
  name: string;
  mobile: string;
  munId: string;
  provId: string;
  photoURL: string;
  createdAt?: Date; // Optional, added by Prisma
}

interface PolygonInfo {
  polType: string;
  name: string;
}

if (!admin.apps.length) {
  admin.initializeApp({
    credential: admin.credential.cert({
      projectId: process.env.FIREBASE_PROJECT_ID,
      privateKey: process.env.FIREBASE_PRIVATE_KEY?.replace(/\\n/g, "\n"),
      clientEmail: process.env.FIREBASE_CLIENT_EMAIL,
      
    }),
  });
}

async function sendFcmNotification(data: Emergency, topicFilter:string) {
  const { emergency, name} = data;
  // const topic ="presroxascot2025"
  try {
    await admin.messaging().send({
      notification: {
        title: "Emergency Reported!",
        body: `${name} reported a ${emergency} incident!`,
      },
      topic: topicFilter,
    });
    console.log("Online FCM notification sent successfully");
  } catch (error) {
    console.error("Failed to send FCM notification:", error);
  }
}


export async function POST(request: Request) {
  const { searchParams } = new URL(request.url);
  const token = searchParams.get("token");

  if (token !== VERIFY_TOKEN) {
    return new NextResponse("Verification failed", { status: 403 });
  }

  try {
    const requestBody = await request.json();

    const { emergency, lat, long, barangay, munName, name, mobile, munId, provId, photoURL, } = requestBody;

    if (!emergency || !lat || !long  || !barangay || !name || !mobile) {
      return NextResponse.json({ error: "Missing required fields" }, { status: 400 });
    }

    const data = {lat, long}

  // Forward the request to the external API
    const externalResponse = await fetch(`${process.env.NEXT_PUBLIC_DOMAIN}/api/places`,
      {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(data),
      }
    );

// Parse and log the external API response
    const externalData = await externalResponse.json();

  
    const filtered = externalData.current?.filter(
  (item: { polType: string; name: string }) => !(item.polType === "mun")
);

 


    //tama ni code para ma check naku ang municipality name
const locationIncident = filtered.length >= 1 ? filtered.map((item: PolygonInfo) => item.name).join(", ") : "Unknow Location";

  //this code to get last name of the array 
    console.log("External API response:", locationIncident);

const topicFilter = externalData.current?.filter(
  (item: { polType: string; name: string }) => (item.polType === "mun")
);

const fcmTopic = topicFilter.map((item:PolygonInfo) => item.name).join(", ")

console.log('topic', fcmTopic)


  
  // Save data to the database using Prisma
    const savedData = await prisma.emergency.create({
      data: { 
        emergency, 
        lat, 
        long, 
        barangay: locationIncident, 
        munName, name, mobile, munId, provId, status: true, verified: false, photoURL },
    });

    // Send FCM notification asynchronously
    sendFcmNotification(savedData, fcmTopic).catch(console.error);

    //send response to the client
    return NextResponse.json(
      { message: "Emergency data saved successfully" },
      { status: 201 }
    );


  } catch (error) {
    console.error("Error during saving data:", error);
    return NextResponse.json({ message: "Failed to save data" }, { status: 500 });
  } finally {
    await prisma.$disconnect();
  }
}